[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#F2F2F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1C1C1E"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
