[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#FFFFFF"
font = "Poppins"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
