[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#141414"
secondaryBackgroundColor = "#11111"
textColor = "#1C1C1E"
font = "Poppins"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
